### ISSUE TITLE
add function `fpr_photo_remove_dupes` to remove duplicated photos before or after photo name appended to end of photo file name by `fpr_photo_rename`

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fpr#42]

**Comment by NewGraphEnvironment** [comment]
High risk function which highlights lots of things.  Ex. when we use the same photo for two different columns it will find those.  Looks like this results in sorting with more than 2 duplicates and removal of unnamed photo (when `remove_renamed = FALSE`)

We will move ahead as is but there may be missing photos here and there so for now we have `sorted_copy` folders on onedrive as backups that have all the duplicates unremoved.  Will remove after reporting is done.  Heads up @Mateo9569

Will put some details in repos as there are some obvious errors that show up

**Comment by Mateo9569** [comment]
Understood, I'll keep an eye out. Should be easy to spot missing photos once we build all the amalgamated photos for each site.

**Comment by NewGraphEnvironment** [comment]
add param to define triplets vs duplicates and switch to build dataframe that shows the results of both

`plyr::filter(dplyr::n()>1)`

```

test_bfpr_photo_remove_dupes <- function(dir_target = NULL,
                                   col_time = date_time_original,
                                   col_photo_name = source_file,
                                   col_model = model,
                                   col_iso = iso,
                                   remove_renamed = FALSE,
                                   ...){
  dat1 <- exifr::read_exif(path = dir_target,recursive=T)  %>%
    janitor::clean_names()  %>%
    dplyr::group_by( {{ col_model }}, {{ col_iso }}, {{ col_time }}) %>%
    dplyr::filter(dplyr::n()>1) %>%
    dplyr::mutate(l = stringr::str_length( {{ col_photo_name }} ))

  if(remove_renamed){
    dat2 <- dat1 %>%
      dplyr::arrange( {{ col_time }}, {{ col_model }}, {{ col_iso }}, desc(l))
  }else if(identical(remove_renamed, FALSE))
    dat2 <- dat1 %>%
      dplyr::arrange( {{ col_time }},{{ col_model }}, {{ col_iso }}, l)

  # dat3 <- dat2 %>%
  #   dplyr::distinct( {{ col_time }}, .keep_all = T)

  # dat3 %>%
  #   dplyr::pull( {{ col_photo_name }}) %>%
  #   purrr::map(file.remove)

}
```

**Comment by NewGraphEnvironment** [comment]
- [ ] add dry run that builds dataframe for understanding potential removals and documenting actual removals
- [ ] add param to define triplets vs duplicates
- [ ] remove photo only when it is in the same directory as the replicates
- [ ] remove only 1 photo for each group of replicates

**Comment by NewGraphEnvironment** [comment]
see https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/issues/36

`fpr_photo_remove_dupes` should only look for dupes in the same file because currently it looks everywhere.  If duplicate is found in another file - the slice function assumes the photos duplicated are in the same site directory and gets rid of a renamed photo!


![image](https://github.com/NewGraphEnvironment/fpr/assets/46538103/c37fb34b-aaed-4b5e-9b87-9932500ec67f)
