### ISSUE TITLE
`fpr_sp_wshd_stats` function no longer works because url that is called is a broken link

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fpr#44]
Seen below is the error message received when trying to run function. When copy and pasting url in function into browser, link is broken. Not sure how to fix because I'm not sure what was in that link to begin with. 

![image](https://github.com/NewGraphEnvironment/fpr/assets/99455166/cd991959-f928-4940-9ee5-47965e5306e7)

**Comment by NewGraphEnvironment** [comment]
Issue is the lookup table used to cross reference degrees to direction (ex 0 degrees = N, 45 degrees = NE, etc.).  We were sourcing a lookup table served from a url provided by university of Minnesota and now it has been pulled down. Options are to remove the dominant watershed aspect from the table built by the function or find or build another lookup table.

**Comment by NewGraphEnvironment** [comment]
this works and is really simple to replace the call to the remote table.  just build a new one. will sub in and close

```
directions <- tibble::tibble( degree_max = seq(0, 337.5 , by=22.5),
                   cardinal = c("N","NNE","NE", "ENE", "E", "ESE", "SE", "SSE",
                     "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"))
```
