### ISSUE TITLE
`fpr_import_pscis` failing with empty spreadsheet.

### ISSUE THREAD

**Issue by newgraph-lschick** [NewGraphEnvironment/fpr#63]
**Issue:**
`fpr_import_pscis` is used in the [Skeena 2023](https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/blob/main/scripts/pscis_tidy.R#L163C1-L165C11) and[ Fraser 2023](https://github.com/NewGraphEnvironment/fish_passage_fraser_2023_reporting/blob/main/scripts/01_pscis_tidy.R#L109C1-L111C11) repo to import the `pscis_phase1.xlsm `spreadsheet as a template, but I am running into errors when the `pscis_phase1.xlsm` is empty, because of the  `lubridate::ymd_hms()` call with an empty date and time. 

**Reprex:** Need to ensure `pscis_phase1.xlsm ` is empty before running this, current `pscis_phase1.xlsm ` in skeena repo contains data.
``` r
library(tidyverse)

template <- fpr::fpr_import_pscis() %>%
  slice(0)
#Warning message:                                                                                                                   
There was 1 warning in `dplyr::mutate()`.
ℹ In argument: `date_time_start = lubridate::ymd_hms(paste0(date, " ", time_start))`.
Caused by warning:
! All formats failed to parse. No formats found. 
```

<sup>Created on 2024-03-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**location:**
I think this is where it is failing, https://github.com/NewGraphEnvironment/fpr/blob/main/R/import.R#L86C7-L86C75. Because since 
`pscis_phase1.xlsm` is empty, `data` and `time_start` are both empty, so `lubridate::ymd_hms()` can't format properly and throws an error. 

**What I've tried:**
- [x] calling `fpr_import_pscis` with a version of `pscis_phase1.xlsm ` that contains data, and it works just fine.

**Comment by NewGraphEnvironment** [comment]
this is a workflow change issue addressed here

https://github.com/NewGraphEnvironment/fish_passage_fraser_2023_reporting/blob/main/scripts/05_pscis_export_submission.R

**Comment by NewGraphEnvironment** [comment]
`fpr::fpr_xref_template_pscis()` can be used as a template

`fpr_import_pscis` shouldl still be good to go for importing the actual data

**Comment by newgraph-lschick** [comment]
okay thanks
