### ISSUE TITLE
`fpr_my_fish_sp` returning `character(0)` when there are multiple species upstream

### ISSUE THREAD

**Issue by lucy-schick** [NewGraphEnvironment/fpr#89]
**Issue:**
Just ran into this issue what editing PSCIS 8543 site memo in skeena 2023 report. 

 PSCIS 8543 has both DV and RB observed upstream, and we can see this in the bcfishpass object, but when calling `fpr_my_fish_sp` it returns `character(0)`. 

To confirm this issue, I also tried with site 8539 which has many species upstream and had the same issue.

```
> my_site <- 8543
> 
> fpr::fpr_my_bcfishpass(col_pull = observedspp_upstr)
[1] "DV;RB"
> 
> fpr::fpr_my_fish_sp()
character(0)
>
``` 

Issue is coming from https://github.com/NewGraphEnvironment/fpr/blob/main/R/report.R#L130C3-L135C27

`dplyr::filter(Code %in% str_to_pull & !Code %in% sp_ignore) ` returns `character(0)` when `str_to_pull` contains more than one species code (ex "DV;RB") because there is obviously no species Code in `freshwaterfish` that is "DV;RB". 

Nevermind!

Issue is because the `strsplit(., ",")` was splitting on `,` but things must have changed and now it should split on `;`

**Fixes:**

Change `strsplit(., ";")` to `strsplit(., ";")` here https://github.com/NewGraphEnvironment/fpr/blob/main/R/report.R#L128C3-L128C25

Will let u change in next set of updates to fpr

**Comment by NewGraphEnvironment** [comment]
Asesom. thank you

If we split on both - results produced in all the old reports shouldn't break when rerun

``` r
stringr::str_split("DV;RB", c(",", ";"))
#> [[1]]
#> [1] "DV;RB"
#> 
#> [[2]]
#> [1] "DV" "RB"
stringr::str_split("DV,RB", c(",", ";"))
#> [[1]]
#> [1] "DV" "RB"
#> 
#> [[2]]
#> [1] "DV,RB"
```

<sup>Created on 2024-05-30 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by NewGraphEnvironment** [comment]
actually - here it is

``` r
stringr::str_split("DV;RB", c(",|;"))
#> [[1]]
#> [1] "DV" "RB"
stringr::str_split("DV,RB", c(",|;"))
#> [[1]]
#> [1] "DV" "RB"
```
will fix and close now
<sup>Created on 2024-05-30 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by NewGraphEnvironment** [comment]
closed with https://github.com/NewGraphEnvironment/fpr/commit/04f43e55dc04e39cc25e1ecdd0dec4818bfd3884
