### ISSUE TITLE
create `fpr_sp_user_modelled_crossing_fixes` fixes

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fpr#93]
Need to turn
`https://github.com/NewGraphEnvironment/bcfishpass/blob/main/data/user_modelled_crossing_fixes.csv` into a spatial file so that we can see sites that have already been reviewed.  Will require calls to `fpr_db_query` and simple join on `modelled_crossing_id` to shared db version of `bcfishpass.crossings_vw` to grab the utms

Ideally reads `data/user_modelled_crossing_fixes.csv` from github url directly with param to burn to `qgis` project of choice.  Probably simplist to burn to individual `gpkg` to start but can consider if we want to have switch to burn direct to `background_layers.gpkg` (or any other geopackage).  Maybe it could be either right of the bat (not sure).  `rfp` currently deals with building `background_layers.gpkg` so can consider that this a function that belongs there (leaning away from that right now though since it is so fp specific).

**Comment by NewGraphEnvironment** [comment]
relevant issue here https://github.com/smnorris/bcfishpass/issues/361

**Comment by smnorris** [comment]
Would adding a columns like `modelled_crossing_review_status` to `crossings_vw` work?

**Comment by smnorris** [comment]
`crossings_vw` already has a ton of columns but does seem useful to have this info there directly - if it has been reviewed, by whom, when, and any notes.

But that said, I'm not sure where the review tracking process is going - CWF is working on that internally and I have no insight at the moment.

**Comment by NewGraphEnvironment** [comment]
Not a bad idea (smarter really) to just add to crossings_vw.  Hadn't actually thought of it. Glad i asked. Not first priority but prob going to need it soon and then it will be and we can spin something if you don't want to take it on. all good either way. i guess you need it too...

**Comment by smnorris** [comment]
I don't need it right now, but it is a simple change. The work would mostly be deciding which columns to retain and updating the documentation.

**Comment by NewGraphEnvironment** [comment]
Awesomely dealt with upstream in `bcfishpass`.  Thanks Norris
